### ISSUE TITLE
unable to unrar Eimages.rar

### ISSUE THREAD

**Issue by sushmarchandran** [liaolianfoka/MET-Meme-A-Multi-modal-Meme-Dataset-Rich-in-Metaphors#1]
Hello! I'm interested in using the dataset you published [here](https://dl.acm.org/doi/10.1145/3477495.3532019). I'm specifically interested in the English memes. I use a Mac and am unable to unrar the Eimages.rar file using standard unrar softwares like The Unarchiver, brew's unrar and RAR Unarchiver. Could you please confirm if you're able to unrar the file and/or please give me access to the images through another source?

**Comment by liaolianfoka** [comment]
I'm sorry that there seems something wrong when download Eimages.rar file without git-lfs because the file is too large.
You can download them here.
https://www.kaggle.com/datasets/liaolianfoka/met-meme

**Comment by sushmarchandran** [comment]
Thank you. This worked! Closing the issue.

**Comment by cmllzll** [comment]
Hello, I am very interested in the dataset you have published. But I am currently unable to implement the operation of the model. May I ask if you can publish the relevant pkl files for reference and learning?
